dist: trusty
sudo: required
language: python
python:
  - "3.6"
addons:
  chrome: stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install pytest-cov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
  - gunicorn app:server --timeout 300 --daemon
  - sleep 5
script: 
  - python -m pytest --cov=./ --cov-config .coveragerc
  - python -m pytest ui_tests/
after_success:
  - codecov
